"""
Tests for AI DJ with persona support and TTS integration.
"""

import json
import tempfile
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

from qfzz.core.llm_router import LLMResponse
from qfzz.dj.ai_dj import AIDJ


@pytest.fixture
def temp_personas_config():
    """Create temporary personas config file."""
    config_data = {
        "personas": {
            "energetic": {
                "name": "Fuzzy Beats",
                "description": "High-energy DJ",
                "voice_id": "alloy",
                "style": "upbeat, enthusiastic",
                "temperature": 0.8,
                "banned_phrases": ["AI", "language model", "generated"],
            },
            "chill": {
                "name": "Smooth Vibes",
                "description": "Laid-back DJ",
                "voice_id": "nova",
                "style": "mellow, smooth",
                "temperature": 0.6,
                "banned_phrases": ["AI", "language model"],
            },
            "intellectual": {
                "name": "Professor Groove",
                "description": "Knowledgeable music historian",
                "voice_id": "onyx",
                "style": "informative, thoughtful",
                "temperature": 0.7,
                "banned_phrases": ["AI", "algorithm"],
            },
        }
    }

    with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False) as f:
        json.dump(config_data, f)
        temp_path = f.name

    yield temp_path

    Path(temp_path).unlink(missing_ok=True)


@pytest.fixture
def mock_llm_router_success():
    """Mock LLM router that always succeeds."""
    with patch("qfzz.dj.ai_dj.LLMRouter") as mock:
        router_instance = MagicMock()
        router_instance.generate.return_value = LLMResponse(
            content="This is an awesome track!",
            provider="google",
            model="gemini-2.0-flash",
            cost=0.0001,
            latency=0.5,
            success=True,
        )
        mock.return_value = router_instance
        yield router_instance


@pytest.fixture
def mock_state_manager():
    """Mock state manager."""
    with patch("qfzz.dj.ai_dj.StateManager") as mock:
        state_instance = MagicMock()
        state_instance.get_dj_memory.return_value = {
            "conversation_history": [],
            "learned_patterns": {},
            "banned_phrases": ["AI", "language model"],
        }
        mock.return_value = state_instance
        yield state_instance


def test_ai_dj_initialization(temp_personas_config, mock_llm_router_success, mock_state_manager):
    """Test AI DJ initialization."""
    dj = AIDJ(persona="energetic", personas_config_path=temp_personas_config)

    assert dj.persona == "energetic"
    assert dj.persona_config["name"] == "Fuzzy Beats"
    assert dj.voice_id == "alloy"
    assert dj.llm_router is not None
    assert dj.state is not None
    assert dj.tts_client is None  # TTS disabled by default


def test_ai_dj_unknown_persona_defaults_to_energetic(
    temp_personas_config, mock_llm_router_success, mock_state_manager
):
    """Test unknown persona defaults to energetic."""
    dj = AIDJ(persona="unknown", personas_config_path=temp_personas_config)

    assert dj.persona == "energetic"
    assert dj.persona_config["name"] == "Fuzzy Beats"


def test_ai_dj_track_introduction(
    temp_personas_config, mock_llm_router_success, mock_state_manager
):
    """Test AI DJ track introduction."""
    dj = AIDJ(persona="energetic", personas_config_path=temp_personas_config)

    track = {
        "title": "Electric Dreams",
        "artist": "Synth Wave",
        "genre": "Electronic",
    }

    intro = dj.introduce_track(track)

    assert len(intro) > 0
    assert isinstance(intro, str)

    # Verify LLM was called
    mock_llm_router_success.generate.assert_called_once()

    # Verify state was updated
    mock_state_manager.add_conversation.assert_called_with(role="dj", content=intro)


def test_ai_dj_banned_phrases_filtered(temp_personas_config, mock_state_manager):
    """Test that banned phrases are filtered from responses."""
    with patch("qfzz.dj.ai_dj.LLMRouter") as mock_router:
        router_instance = MagicMock()
        # Response contains banned phrases
        router_instance.generate.return_value = LLMResponse(
            content="This track was generated by AI using a language model!",
            provider="google",
            model="gemini-2.0-flash",
            cost=0.0001,
            latency=0.5,
            success=True,
        )
        mock_router.return_value = router_instance

        dj = AIDJ(persona="energetic", personas_config_path=temp_personas_config)

        track = {"title": "Test Song", "artist": "Test Artist", "genre": "Rock"}
        intro = dj.introduce_track(track)

        # Banned phrases should be removed
        assert "AI" not in intro
        assert "language model" not in intro
        assert "generated" not in intro


def test_ai_dj_listener_response(temp_personas_config, mock_llm_router_success, mock_state_manager):
    """Test AI DJ responding to listener."""
    dj = AIDJ(persona="chill", personas_config_path=temp_personas_config)

    request = "Can you play some jazz?"
    response = dj.respond_to_listener(request)

    assert len(response) > 0
    assert isinstance(response, str)

    # Verify state was updated with both listener and DJ messages
    assert mock_state_manager.add_conversation.call_count == 2


def test_ai_dj_transition_generation(
    temp_personas_config, mock_llm_router_success, mock_state_manager
):
    """Test AI DJ transition between tracks."""
    dj = AIDJ(persona="energetic", personas_config_path=temp_personas_config)

    current_track = {
        "title": "Midnight City",
        "artist": "M83",
        "genre": "Electronic",
    }
    next_track = {
        "title": "Digital Love",
        "artist": "Daft Punk",
        "genre": "Electronic",
    }

    transition = dj.generate_transition(current_track, next_track)

    assert len(transition) > 0
    assert isinstance(transition, str)

    # Verify state was updated
    mock_state_manager.add_conversation.assert_called_with(role="dj", content=transition)


def test_ai_dj_station_id(temp_personas_config, mock_llm_router_success, mock_state_manager):
    """Test AI DJ station identification."""
    dj = AIDJ(persona="energetic", personas_config_path=temp_personas_config)

    station_id = dj.generate_station_id()

    assert len(station_id) > 0
    assert isinstance(station_id, str)

    # Verify state was updated
    mock_state_manager.add_conversation.assert_called_with(role="dj", content=station_id)


def test_different_personas_have_different_configs(
    temp_personas_config, mock_llm_router_success, mock_state_manager
):
    """Test that different personas have different configurations."""
    dj_energetic = AIDJ(persona="energetic", personas_config_path=temp_personas_config)
    dj_chill = AIDJ(persona="chill", personas_config_path=temp_personas_config)

    assert dj_energetic.persona_config["name"] != dj_chill.persona_config["name"]
    assert dj_energetic.persona_config["temperature"] != dj_chill.persona_config["temperature"]
    assert dj_energetic.voice_id != dj_chill.voice_id


def test_ai_dj_fallback_on_llm_failure(temp_personas_config, mock_state_manager):
    """Test AI DJ uses fallback when LLM fails."""
    with patch("qfzz.dj.ai_dj.LLMRouter") as mock_router:
        router_instance = MagicMock()
        # LLM fails
        router_instance.generate.return_value = LLMResponse(
            content="",
            provider="none",
            model="",
            cost=0.0,
            latency=0.0,
            success=False,
            error="All providers failed",
        )
        mock_router.return_value = router_instance

        dj = AIDJ(persona="energetic", personas_config_path=temp_personas_config)

        track = {"title": "Test Song", "artist": "Test Artist", "genre": "Rock"}
        intro = dj.introduce_track(track)

        # Should get fallback intro
        assert len(intro) > 0
        assert "Test Song" in intro or "Test Artist" in intro


def test_ai_dj_synthesize_speech_disabled_by_default(
    temp_personas_config, mock_llm_router_success, mock_state_manager
):
    """Test that TTS is disabled by default."""
    dj = AIDJ(persona="energetic", personas_config_path=temp_personas_config)

    audio = dj.synthesize_speech("Hello world")

    assert audio is None
    assert dj.tts_client is None


@patch("qfzz.dj.ai_dj.TTSClient")
def test_ai_dj_synthesize_speech_enabled(
    mock_tts_client,
    temp_personas_config,
    mock_llm_router_success,
    mock_state_manager,
):
    """Test that TTS can be enabled."""
    tts_instance = MagicMock()
    tts_instance.is_available.return_value = True
    tts_instance.synthesize.return_value = b"audio_data"
    mock_tts_client.return_value = tts_instance

    dj = AIDJ(
        persona="energetic",
        enable_tts=True,
        personas_config_path=temp_personas_config,
    )

    audio = dj.synthesize_speech("Hello world")

    assert audio == b"audio_data"
    tts_instance.synthesize.assert_called_once_with("Hello world", voice_id="alloy")


def test_ai_dj_get_persona_info(temp_personas_config, mock_llm_router_success, mock_state_manager):
    """Test getting persona information."""
    dj = AIDJ(persona="intellectual", personas_config_path=temp_personas_config)

    assert dj.get_persona_name() == "Professor Groove"
    assert "music historian" in dj.get_persona_description()


def test_ai_dj_get_available_personas(
    temp_personas_config, mock_llm_router_success, mock_state_manager
):
    """Test getting list of available personas."""
    dj = AIDJ(persona="energetic", personas_config_path=temp_personas_config)

    personas = dj.get_available_personas()

    assert "energetic" in personas
    assert "chill" in personas
    assert "intellectual" in personas


def test_ai_dj_custom_voice_id(temp_personas_config, mock_llm_router_success, mock_state_manager):
    """Test that custom voice ID overrides persona default."""
    dj = AIDJ(
        persona="energetic",
        voice_id="custom_voice",
        personas_config_path=temp_personas_config,
    )

    assert dj.voice_id == "custom_voice"


def test_ai_dj_missing_config_uses_defaults(mock_llm_router_success, mock_state_manager):
    """Test that missing config file uses defaults."""
    dj = AIDJ(persona="energetic", personas_config_path="/nonexistent/path/config.json")

    assert dj.persona == "energetic"
    assert dj.persona_config is not None
    assert "name" in dj.persona_config


@pytest.mark.parametrize("persona", ["energetic", "chill", "intellectual"])
def test_ai_dj_all_personas_work(
    persona, temp_personas_config, mock_llm_router_success, mock_state_manager
):
    """Test that all personas can be initialized and used."""
    dj = AIDJ(persona=persona, personas_config_path=temp_personas_config)

    track = {"title": "Test Song", "artist": "Test Artist", "genre": "Rock"}
    intro = dj.introduce_track(track)

    assert len(intro) > 0
    assert dj.persona == persona
